#!/usr/bin/env node
// scripts/release.js — Create a GitHub release with install instructions and SHA256 checksums
//
// Usage:
//   node scripts/release.js "Release title" "## What's New\n- Feature 1\n- Feature 2"
//
// Or run without args for defaults.
// Requires: gh CLI (https://cli.github.com) authenticated

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execSync } = require('child_process');

const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf-8'));
const version = pkg.version;
const tag = `v${version}`;
const distDir = path.join(__dirname, '..', 'dist');

const installerName = `CW-CAT-Setup-${version}.exe`;
const portableName = `CW-CAT-${version}-portable.exe`;
const latestYmlName = 'latest.yml';
const installerPath = path.join(distDir, installerName);
const portablePath = path.join(distDir, portableName);
const latestYmlPath = path.join(distDir, latestYmlName);

function sha256(filePath) {
  const data = fs.readFileSync(filePath);
  return crypto.createHash('sha256').update(data).digest('hex');
}

function main() {
  const assets = [];
  if (fs.existsSync(installerPath)) {
    assets.push({ path: installerPath, name: installerName, hash: sha256(installerPath) });
  } else {
    console.error(`ERROR: Installer not found: ${installerPath}`);
    console.error('Run "npm run dist:win" first.');
    process.exit(1);
  }
  if (fs.existsSync(portablePath)) {
    assets.push({ path: portablePath, name: portableName, hash: sha256(portablePath) });
  }
  if (fs.existsSync(latestYmlPath)) {
    assets.push({ path: latestYmlPath, name: latestYmlName, hash: null });
  } else {
    console.warn('WARNING: latest.yml not found — electron-updater auto-update will not work.');
    console.warn('This file is generated by electron-builder alongside the installer.');
  }

  const title = process.argv[2] || `${tag} beta`;
  const whatsNew = process.argv[3] || '<!-- Add release notes here -->';

  const checksums = assets.filter(a => a.hash).map(a => `| \`${a.name}\` | \`${a.hash}\` |`).join('\n');

  const body = `${whatsNew}

---

## Install

1. Download **\`${installerName}\`** below${assets.length > 1 ? ' (or the portable version)' : ''}
2. Run the installer — Windows SmartScreen may show **"Windows protected your PC"**
   - Click **More info** then **Run anyway**
   - This is normal for unsigned apps
3. CW CAT will launch automatically after install

## SHA-256 Checksums

| File | SHA-256 |
|------|---------|
${checksums}

**Full Changelog**: https://github.com/Waffleslop/cw-cat/compare/v${getPreviousTag()}...${tag}`;

  const bodyFile = path.join(distDir, 'release-notes.md');
  fs.writeFileSync(bodyFile, body, 'utf-8');

  console.log(`\nCreating release ${tag}: ${title}`);
  console.log(`Assets: ${assets.map(a => a.name).join(', ')}`);
  console.log(`Checksums:`);
  assets.forEach(a => console.log(`  ${a.name}: ${a.hash}`));
  console.log('');

  const assetArgs = assets.map(a => `"${a.path}"`).join(' ');
  // --latest: override GitHub's auto-prerelease detection for beta tags.
  // Without this, GitHub marks "beta" tags as pre-release, which breaks
  // electron-updater's /releases/latest endpoint (returns 404).
  const cmd = `gh release create "${tag}" --latest --title "${title}" --notes-file "${bodyFile}" ${assetArgs}`;

  try {
    console.log(`Running: ${cmd}\n`);
    execSync(cmd, { stdio: 'inherit', cwd: path.join(__dirname, '..') });
    console.log(`\nRelease ${tag} created successfully!`);
  } catch (err) {
    console.error('Failed to create release. Check gh auth status.');
    process.exit(1);
  } finally {
    try { fs.unlinkSync(bodyFile); } catch { /* ignore */ }
  }
}

function getPreviousTag() {
  try {
    const tags = execSync('git tag --sort=-v:refname', { encoding: 'utf-8' }).trim().split('\n');
    for (const t of tags) {
      if (t.trim() && t.trim() !== tag) return t.trim();
    }
  } catch { /* ignore */ }
  const parts = version.split('.').map(Number);
  if (parts[2] > 0) parts[2]--;
  else if (parts[1] > 0) { parts[1]--; parts[2] = 0; }
  return `v${parts.join('.')}`;
}

main();
